import numpy as np
m=int(input("enter number of rows : "))
n=int(input("enter number of columns : "))
matrix=np.ndarray(shape=(m,n) , dtype=int)
print("enter {} numbers : ".format(m*n))
for i in range(m):
    for j in range(n):
        matrix[i][j]=int(input())
print("entered matrix : ")
print(matrix)
print()
temp1=np.sort(matrix,axis=0)
print("sorted matrix along first axis : ")
print(temp1)
print()
temp2=np.sort(matrix,axis=1)
print("sorted matrix along second axis : ")
print(temp2)
print()
print("sorted matrix in flatten : ")
temp3=np.sort(matrix.flatten())
print(temp3)